project:
  type: book
  # see GitHub Pages (publishing) https://quarto.org/docs/publishing/github-pages.html
  output-dir: docs

book:
  title: "使用 Python 進行地理計算"
  page-footer: "【使用 Python 進行地理計算】作者 Michael Dorman, Anita Graser, Jakub Nowosad, 及 Robin Lovelace"
  # number-sections: true
  author: "Michael Dorman, Anita Graser, Jakub Nowosad, Robin Lovelace"
  description: | 
    使用 Python 處理地理資料的入門資源
  cover-image: https://geocompx.org/static/img/book_cover_py.png
  site-url: https://py.geocompx.org
  repo-url: https://github.com/geocompx/geocompy/
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  google-analytics: G-ZEMGTY4VV3
  favicon: favicon-32x32.png
  chapters:
    - index.qmd
    - preface.qmd
    - 01-spatial-data.qmd
    - 02-attribute-operations.qmd
    - 03-spatial-operations.qmd
    - 04-geometry-operations.qmd
    - 05-raster-vector.qmd
    - 06-reproj.qmd
    - 07-read-write.qmd
    - 08-mapping.qmd
    - references.qmd

format:
  html: 
    theme: flatly
    code-link: true
    template-partials: [helpers/toc.html, helpers/title-block.html]
    toc-title: "本頁大綱"
    code-overflow: wrap
    toc-depth: 4
    css: [helpers/mystyle.css]
  # pdf:
  #   documentclass: krantz
  #   monofont: 'Source Code Pro'
  #   monofontoptions: 
  #     - Scale=0.7
  #   pdf-engine: xelatex
  #   keep-tex: true
  #   number-sections: true
  #   top-level-division: chapter
  #   include-before-body: helpers/before_body.tex
  #   include-in-header: 
  #     text: |
  #       \AtBeginEnvironment{longtable}{\footnotesize}
  #       \usepackage{makeidx}
  #       \usepackage{gensymb}
  #       \usepackage{cjhebrew}
  #       \makeindex
  #   include-after-body: 
  #     text: |
  #       \printindex

jupyter: python3
bibliography: geocompr.bib
